# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-251834-andresitocc99/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu3eg-sbva484-1-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog {
      /tools/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog {
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/342a/hdl/floating_point_v7_1_rfs.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_am_addmul_12ns_11ns_8ns_19_4_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_ama_addmuladd_12ns_11ns_8ns_8ns_19_4_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_CONTROL_BUS_s_axi.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_faddfsub_32ns_32ns_32_5_full_dsp_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_fcmp_32ns_32ns_1_2_no_dsp_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_flow_control_loop_pipe_sequential_init.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_fmul_32ns_32ns_32_4_max_dsp_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_fsqrt_32ns_32ns_32_10_no_dsp_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_hls_deadlock_idx0_monitor.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_L1_L2_L3.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_L3.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_VITIS_LOOP_83_1_VITIS_LOOP_84_2_VITIS_LOOP_85_s.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_VITIS_LOOP_98_5.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_VITIS_LOOP_113_6.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_VITIS_LOOP_148_7.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_image_RAM_AUTO_1R1W.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_mul_mul_19s_8ns_19_4_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_regslice_both.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_sitofp_32ns_32_4_no_dsp_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped_uitofp_32ns_32_4_no_dsp_1.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/verilog/hyperspectral_hw_wrapped.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/ip/hyperspectral_hw_wrapped_fsqrt_32ns_32ns_32_10_no_dsp_1_ip.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/ip/hyperspectral_hw_wrapped_uitofp_32ns_32_4_no_dsp_1_ip.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/ip/hyperspectral_hw_wrapped_faddfsub_32ns_32ns_32_5_full_dsp_1_ip.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/ip/hyperspectral_hw_wrapped_sitofp_32ns_32_4_no_dsp_1_ip.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/ip/hyperspectral_hw_wrapped_fcmp_32ns_32ns_1_2_no_dsp_1_ip.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/33d5/hdl/ip/hyperspectral_hw_wrapped_fmul_32ns_32ns_32_4_max_dsp_1_ip.v
      /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ip/design_1_hyperspectral_hw_wra_0_0/synth/design_1_hyperspectral_hw_wra_0_0.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2022.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xbip_utils_v3_0_10 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_6 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_6 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_6 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_6 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_6 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_18 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/ab19/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_1_14 /home/andresitocc99/Documentos/Vivado/hyperspectral/hyperspectral.gen/sources_1/bd/design_1/ipshared/342a/hdl/floating_point_v7_1_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_hyperspectral_hw_wra_0_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    set_param edifin.funnel true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-251834-andresitocc99/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
