-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_VITIS_LOOP_85_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    closest_pixel_V_359_04_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_360_06_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_361_08_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_362_010_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_363_012_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_364_014_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_365_016_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_366_018_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_367_020_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_368_022_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_369_024_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_370_026_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_371_028_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_372_030_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_373_032_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_374_034_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_375_036_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_376_038_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_377_040_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_378_042_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_379_044_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_380_046_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_381_048_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_382_050_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_383_052_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_384_054_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_385_056_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_386_058_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_387_060_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_388_062_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_389_064_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_390_066_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_391_068_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_392_070_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_393_072_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_394_074_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_395_076_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_396_078_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_397_080_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_398_082_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_399_084_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_400_086_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_401_088_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_402_090_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_403_092_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_404_094_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_405_096_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_406_098_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_407_0100_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_408_0102_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_409_0104_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_410_0106_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_411_0108_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_412_0110_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_413_0112_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_414_0114_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_415_0116_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_416_0118_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_417_0120_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_418_0122_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_419_0124_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_420_0126_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_421_0128_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_422_0130_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_423_0132_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_424_0134_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_425_0136_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_426_0138_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_427_0140_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_428_0142_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_429_0144_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_430_0146_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_431_0148_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_432_0150_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_433_0152_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_434_0154_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_435_0156_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_436_0158_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_437_0160_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_438_0162_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_439_0164_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_440_0166_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_441_0168_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_442_0170_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_443_0172_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_444_0174_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_445_0176_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_446_0178_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_447_0180_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_448_0182_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_449_05_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_450_07_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_451_09_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_452_011_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_453_013_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_454_015_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_455_017_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_456_019_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_457_021_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_458_023_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_459_025_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_460_027_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_461_029_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_462_031_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_463_033_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_464_035_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_465_037_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_466_039_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_467_041_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_468_043_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_469_045_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_470_047_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_471_049_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_472_051_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_473_053_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_474_055_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_475_057_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_476_059_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_477_061_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_478_063_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_479_065_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_480_067_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_481_069_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_482_071_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_483_073_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_484_075_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_485_077_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_486_079_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_487_081_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_488_083_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_489_085_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_490_087_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_491_089_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_492_091_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_493_093_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_494_095_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_495_097_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_496_099_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_497_0101_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_498_0103_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_499_0105_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_500_0107_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_501_0109_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_502_0111_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_503_0113_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_504_0115_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_505_0117_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_506_0119_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_507_0121_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_508_0123_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_509_0125_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_510_0127_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_511_0129_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_512_0131_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_513_0133_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_514_0135_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_515_0137_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_516_0139_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_517_0141_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_518_0143_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_519_0145_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_520_0147_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_521_0149_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_522_0151_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_523_0153_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_524_0155_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_525_0157_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_526_0159_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_527_0161_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_528_0163_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_529_0165_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_530_0167_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_531_0169_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_532_0171_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_533_0173_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_534_0175_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_535_0177_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_536_0179_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_537_0181_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    closest_pixel_V_538_0183_reload : IN STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of hyperspectral_hw_wrapped_hyperspectral_hw_wrapped_Pipeline_VITIS_LOOP_85_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_5 : STD_LOGIC_VECTOR (4 downto 0) := "00101";
    constant ap_const_lv5_6 : STD_LOGIC_VECTOR (4 downto 0) := "00110";
    constant ap_const_lv8_B4 : STD_LOGIC_VECTOR (7 downto 0) := "10110100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_B1 : STD_LOGIC_VECTOR (7 downto 0) := "10110001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln85_fu_1546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_s_fu_1552_p181 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_reg_2314 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_27_fu_1916_p181 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_27_reg_2319 : STD_LOGIC_VECTOR (15 downto 0);
    signal e_last_V_fu_2280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal e_last_V_reg_2324 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_424 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln85_fu_2286_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hyperspectral_hw_wrapped_mux_1798_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        din33_WIDTH : INTEGER;
        din34_WIDTH : INTEGER;
        din35_WIDTH : INTEGER;
        din36_WIDTH : INTEGER;
        din37_WIDTH : INTEGER;
        din38_WIDTH : INTEGER;
        din39_WIDTH : INTEGER;
        din40_WIDTH : INTEGER;
        din41_WIDTH : INTEGER;
        din42_WIDTH : INTEGER;
        din43_WIDTH : INTEGER;
        din44_WIDTH : INTEGER;
        din45_WIDTH : INTEGER;
        din46_WIDTH : INTEGER;
        din47_WIDTH : INTEGER;
        din48_WIDTH : INTEGER;
        din49_WIDTH : INTEGER;
        din50_WIDTH : INTEGER;
        din51_WIDTH : INTEGER;
        din52_WIDTH : INTEGER;
        din53_WIDTH : INTEGER;
        din54_WIDTH : INTEGER;
        din55_WIDTH : INTEGER;
        din56_WIDTH : INTEGER;
        din57_WIDTH : INTEGER;
        din58_WIDTH : INTEGER;
        din59_WIDTH : INTEGER;
        din60_WIDTH : INTEGER;
        din61_WIDTH : INTEGER;
        din62_WIDTH : INTEGER;
        din63_WIDTH : INTEGER;
        din64_WIDTH : INTEGER;
        din65_WIDTH : INTEGER;
        din66_WIDTH : INTEGER;
        din67_WIDTH : INTEGER;
        din68_WIDTH : INTEGER;
        din69_WIDTH : INTEGER;
        din70_WIDTH : INTEGER;
        din71_WIDTH : INTEGER;
        din72_WIDTH : INTEGER;
        din73_WIDTH : INTEGER;
        din74_WIDTH : INTEGER;
        din75_WIDTH : INTEGER;
        din76_WIDTH : INTEGER;
        din77_WIDTH : INTEGER;
        din78_WIDTH : INTEGER;
        din79_WIDTH : INTEGER;
        din80_WIDTH : INTEGER;
        din81_WIDTH : INTEGER;
        din82_WIDTH : INTEGER;
        din83_WIDTH : INTEGER;
        din84_WIDTH : INTEGER;
        din85_WIDTH : INTEGER;
        din86_WIDTH : INTEGER;
        din87_WIDTH : INTEGER;
        din88_WIDTH : INTEGER;
        din89_WIDTH : INTEGER;
        din90_WIDTH : INTEGER;
        din91_WIDTH : INTEGER;
        din92_WIDTH : INTEGER;
        din93_WIDTH : INTEGER;
        din94_WIDTH : INTEGER;
        din95_WIDTH : INTEGER;
        din96_WIDTH : INTEGER;
        din97_WIDTH : INTEGER;
        din98_WIDTH : INTEGER;
        din99_WIDTH : INTEGER;
        din100_WIDTH : INTEGER;
        din101_WIDTH : INTEGER;
        din102_WIDTH : INTEGER;
        din103_WIDTH : INTEGER;
        din104_WIDTH : INTEGER;
        din105_WIDTH : INTEGER;
        din106_WIDTH : INTEGER;
        din107_WIDTH : INTEGER;
        din108_WIDTH : INTEGER;
        din109_WIDTH : INTEGER;
        din110_WIDTH : INTEGER;
        din111_WIDTH : INTEGER;
        din112_WIDTH : INTEGER;
        din113_WIDTH : INTEGER;
        din114_WIDTH : INTEGER;
        din115_WIDTH : INTEGER;
        din116_WIDTH : INTEGER;
        din117_WIDTH : INTEGER;
        din118_WIDTH : INTEGER;
        din119_WIDTH : INTEGER;
        din120_WIDTH : INTEGER;
        din121_WIDTH : INTEGER;
        din122_WIDTH : INTEGER;
        din123_WIDTH : INTEGER;
        din124_WIDTH : INTEGER;
        din125_WIDTH : INTEGER;
        din126_WIDTH : INTEGER;
        din127_WIDTH : INTEGER;
        din128_WIDTH : INTEGER;
        din129_WIDTH : INTEGER;
        din130_WIDTH : INTEGER;
        din131_WIDTH : INTEGER;
        din132_WIDTH : INTEGER;
        din133_WIDTH : INTEGER;
        din134_WIDTH : INTEGER;
        din135_WIDTH : INTEGER;
        din136_WIDTH : INTEGER;
        din137_WIDTH : INTEGER;
        din138_WIDTH : INTEGER;
        din139_WIDTH : INTEGER;
        din140_WIDTH : INTEGER;
        din141_WIDTH : INTEGER;
        din142_WIDTH : INTEGER;
        din143_WIDTH : INTEGER;
        din144_WIDTH : INTEGER;
        din145_WIDTH : INTEGER;
        din146_WIDTH : INTEGER;
        din147_WIDTH : INTEGER;
        din148_WIDTH : INTEGER;
        din149_WIDTH : INTEGER;
        din150_WIDTH : INTEGER;
        din151_WIDTH : INTEGER;
        din152_WIDTH : INTEGER;
        din153_WIDTH : INTEGER;
        din154_WIDTH : INTEGER;
        din155_WIDTH : INTEGER;
        din156_WIDTH : INTEGER;
        din157_WIDTH : INTEGER;
        din158_WIDTH : INTEGER;
        din159_WIDTH : INTEGER;
        din160_WIDTH : INTEGER;
        din161_WIDTH : INTEGER;
        din162_WIDTH : INTEGER;
        din163_WIDTH : INTEGER;
        din164_WIDTH : INTEGER;
        din165_WIDTH : INTEGER;
        din166_WIDTH : INTEGER;
        din167_WIDTH : INTEGER;
        din168_WIDTH : INTEGER;
        din169_WIDTH : INTEGER;
        din170_WIDTH : INTEGER;
        din171_WIDTH : INTEGER;
        din172_WIDTH : INTEGER;
        din173_WIDTH : INTEGER;
        din174_WIDTH : INTEGER;
        din175_WIDTH : INTEGER;
        din176_WIDTH : INTEGER;
        din177_WIDTH : INTEGER;
        din178_WIDTH : INTEGER;
        din179_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        din3 : IN STD_LOGIC_VECTOR (15 downto 0);
        din4 : IN STD_LOGIC_VECTOR (15 downto 0);
        din5 : IN STD_LOGIC_VECTOR (15 downto 0);
        din6 : IN STD_LOGIC_VECTOR (15 downto 0);
        din7 : IN STD_LOGIC_VECTOR (15 downto 0);
        din8 : IN STD_LOGIC_VECTOR (15 downto 0);
        din9 : IN STD_LOGIC_VECTOR (15 downto 0);
        din10 : IN STD_LOGIC_VECTOR (15 downto 0);
        din11 : IN STD_LOGIC_VECTOR (15 downto 0);
        din12 : IN STD_LOGIC_VECTOR (15 downto 0);
        din13 : IN STD_LOGIC_VECTOR (15 downto 0);
        din14 : IN STD_LOGIC_VECTOR (15 downto 0);
        din15 : IN STD_LOGIC_VECTOR (15 downto 0);
        din16 : IN STD_LOGIC_VECTOR (15 downto 0);
        din17 : IN STD_LOGIC_VECTOR (15 downto 0);
        din18 : IN STD_LOGIC_VECTOR (15 downto 0);
        din19 : IN STD_LOGIC_VECTOR (15 downto 0);
        din20 : IN STD_LOGIC_VECTOR (15 downto 0);
        din21 : IN STD_LOGIC_VECTOR (15 downto 0);
        din22 : IN STD_LOGIC_VECTOR (15 downto 0);
        din23 : IN STD_LOGIC_VECTOR (15 downto 0);
        din24 : IN STD_LOGIC_VECTOR (15 downto 0);
        din25 : IN STD_LOGIC_VECTOR (15 downto 0);
        din26 : IN STD_LOGIC_VECTOR (15 downto 0);
        din27 : IN STD_LOGIC_VECTOR (15 downto 0);
        din28 : IN STD_LOGIC_VECTOR (15 downto 0);
        din29 : IN STD_LOGIC_VECTOR (15 downto 0);
        din30 : IN STD_LOGIC_VECTOR (15 downto 0);
        din31 : IN STD_LOGIC_VECTOR (15 downto 0);
        din32 : IN STD_LOGIC_VECTOR (15 downto 0);
        din33 : IN STD_LOGIC_VECTOR (15 downto 0);
        din34 : IN STD_LOGIC_VECTOR (15 downto 0);
        din35 : IN STD_LOGIC_VECTOR (15 downto 0);
        din36 : IN STD_LOGIC_VECTOR (15 downto 0);
        din37 : IN STD_LOGIC_VECTOR (15 downto 0);
        din38 : IN STD_LOGIC_VECTOR (15 downto 0);
        din39 : IN STD_LOGIC_VECTOR (15 downto 0);
        din40 : IN STD_LOGIC_VECTOR (15 downto 0);
        din41 : IN STD_LOGIC_VECTOR (15 downto 0);
        din42 : IN STD_LOGIC_VECTOR (15 downto 0);
        din43 : IN STD_LOGIC_VECTOR (15 downto 0);
        din44 : IN STD_LOGIC_VECTOR (15 downto 0);
        din45 : IN STD_LOGIC_VECTOR (15 downto 0);
        din46 : IN STD_LOGIC_VECTOR (15 downto 0);
        din47 : IN STD_LOGIC_VECTOR (15 downto 0);
        din48 : IN STD_LOGIC_VECTOR (15 downto 0);
        din49 : IN STD_LOGIC_VECTOR (15 downto 0);
        din50 : IN STD_LOGIC_VECTOR (15 downto 0);
        din51 : IN STD_LOGIC_VECTOR (15 downto 0);
        din52 : IN STD_LOGIC_VECTOR (15 downto 0);
        din53 : IN STD_LOGIC_VECTOR (15 downto 0);
        din54 : IN STD_LOGIC_VECTOR (15 downto 0);
        din55 : IN STD_LOGIC_VECTOR (15 downto 0);
        din56 : IN STD_LOGIC_VECTOR (15 downto 0);
        din57 : IN STD_LOGIC_VECTOR (15 downto 0);
        din58 : IN STD_LOGIC_VECTOR (15 downto 0);
        din59 : IN STD_LOGIC_VECTOR (15 downto 0);
        din60 : IN STD_LOGIC_VECTOR (15 downto 0);
        din61 : IN STD_LOGIC_VECTOR (15 downto 0);
        din62 : IN STD_LOGIC_VECTOR (15 downto 0);
        din63 : IN STD_LOGIC_VECTOR (15 downto 0);
        din64 : IN STD_LOGIC_VECTOR (15 downto 0);
        din65 : IN STD_LOGIC_VECTOR (15 downto 0);
        din66 : IN STD_LOGIC_VECTOR (15 downto 0);
        din67 : IN STD_LOGIC_VECTOR (15 downto 0);
        din68 : IN STD_LOGIC_VECTOR (15 downto 0);
        din69 : IN STD_LOGIC_VECTOR (15 downto 0);
        din70 : IN STD_LOGIC_VECTOR (15 downto 0);
        din71 : IN STD_LOGIC_VECTOR (15 downto 0);
        din72 : IN STD_LOGIC_VECTOR (15 downto 0);
        din73 : IN STD_LOGIC_VECTOR (15 downto 0);
        din74 : IN STD_LOGIC_VECTOR (15 downto 0);
        din75 : IN STD_LOGIC_VECTOR (15 downto 0);
        din76 : IN STD_LOGIC_VECTOR (15 downto 0);
        din77 : IN STD_LOGIC_VECTOR (15 downto 0);
        din78 : IN STD_LOGIC_VECTOR (15 downto 0);
        din79 : IN STD_LOGIC_VECTOR (15 downto 0);
        din80 : IN STD_LOGIC_VECTOR (15 downto 0);
        din81 : IN STD_LOGIC_VECTOR (15 downto 0);
        din82 : IN STD_LOGIC_VECTOR (15 downto 0);
        din83 : IN STD_LOGIC_VECTOR (15 downto 0);
        din84 : IN STD_LOGIC_VECTOR (15 downto 0);
        din85 : IN STD_LOGIC_VECTOR (15 downto 0);
        din86 : IN STD_LOGIC_VECTOR (15 downto 0);
        din87 : IN STD_LOGIC_VECTOR (15 downto 0);
        din88 : IN STD_LOGIC_VECTOR (15 downto 0);
        din89 : IN STD_LOGIC_VECTOR (15 downto 0);
        din90 : IN STD_LOGIC_VECTOR (15 downto 0);
        din91 : IN STD_LOGIC_VECTOR (15 downto 0);
        din92 : IN STD_LOGIC_VECTOR (15 downto 0);
        din93 : IN STD_LOGIC_VECTOR (15 downto 0);
        din94 : IN STD_LOGIC_VECTOR (15 downto 0);
        din95 : IN STD_LOGIC_VECTOR (15 downto 0);
        din96 : IN STD_LOGIC_VECTOR (15 downto 0);
        din97 : IN STD_LOGIC_VECTOR (15 downto 0);
        din98 : IN STD_LOGIC_VECTOR (15 downto 0);
        din99 : IN STD_LOGIC_VECTOR (15 downto 0);
        din100 : IN STD_LOGIC_VECTOR (15 downto 0);
        din101 : IN STD_LOGIC_VECTOR (15 downto 0);
        din102 : IN STD_LOGIC_VECTOR (15 downto 0);
        din103 : IN STD_LOGIC_VECTOR (15 downto 0);
        din104 : IN STD_LOGIC_VECTOR (15 downto 0);
        din105 : IN STD_LOGIC_VECTOR (15 downto 0);
        din106 : IN STD_LOGIC_VECTOR (15 downto 0);
        din107 : IN STD_LOGIC_VECTOR (15 downto 0);
        din108 : IN STD_LOGIC_VECTOR (15 downto 0);
        din109 : IN STD_LOGIC_VECTOR (15 downto 0);
        din110 : IN STD_LOGIC_VECTOR (15 downto 0);
        din111 : IN STD_LOGIC_VECTOR (15 downto 0);
        din112 : IN STD_LOGIC_VECTOR (15 downto 0);
        din113 : IN STD_LOGIC_VECTOR (15 downto 0);
        din114 : IN STD_LOGIC_VECTOR (15 downto 0);
        din115 : IN STD_LOGIC_VECTOR (15 downto 0);
        din116 : IN STD_LOGIC_VECTOR (15 downto 0);
        din117 : IN STD_LOGIC_VECTOR (15 downto 0);
        din118 : IN STD_LOGIC_VECTOR (15 downto 0);
        din119 : IN STD_LOGIC_VECTOR (15 downto 0);
        din120 : IN STD_LOGIC_VECTOR (15 downto 0);
        din121 : IN STD_LOGIC_VECTOR (15 downto 0);
        din122 : IN STD_LOGIC_VECTOR (15 downto 0);
        din123 : IN STD_LOGIC_VECTOR (15 downto 0);
        din124 : IN STD_LOGIC_VECTOR (15 downto 0);
        din125 : IN STD_LOGIC_VECTOR (15 downto 0);
        din126 : IN STD_LOGIC_VECTOR (15 downto 0);
        din127 : IN STD_LOGIC_VECTOR (15 downto 0);
        din128 : IN STD_LOGIC_VECTOR (15 downto 0);
        din129 : IN STD_LOGIC_VECTOR (15 downto 0);
        din130 : IN STD_LOGIC_VECTOR (15 downto 0);
        din131 : IN STD_LOGIC_VECTOR (15 downto 0);
        din132 : IN STD_LOGIC_VECTOR (15 downto 0);
        din133 : IN STD_LOGIC_VECTOR (15 downto 0);
        din134 : IN STD_LOGIC_VECTOR (15 downto 0);
        din135 : IN STD_LOGIC_VECTOR (15 downto 0);
        din136 : IN STD_LOGIC_VECTOR (15 downto 0);
        din137 : IN STD_LOGIC_VECTOR (15 downto 0);
        din138 : IN STD_LOGIC_VECTOR (15 downto 0);
        din139 : IN STD_LOGIC_VECTOR (15 downto 0);
        din140 : IN STD_LOGIC_VECTOR (15 downto 0);
        din141 : IN STD_LOGIC_VECTOR (15 downto 0);
        din142 : IN STD_LOGIC_VECTOR (15 downto 0);
        din143 : IN STD_LOGIC_VECTOR (15 downto 0);
        din144 : IN STD_LOGIC_VECTOR (15 downto 0);
        din145 : IN STD_LOGIC_VECTOR (15 downto 0);
        din146 : IN STD_LOGIC_VECTOR (15 downto 0);
        din147 : IN STD_LOGIC_VECTOR (15 downto 0);
        din148 : IN STD_LOGIC_VECTOR (15 downto 0);
        din149 : IN STD_LOGIC_VECTOR (15 downto 0);
        din150 : IN STD_LOGIC_VECTOR (15 downto 0);
        din151 : IN STD_LOGIC_VECTOR (15 downto 0);
        din152 : IN STD_LOGIC_VECTOR (15 downto 0);
        din153 : IN STD_LOGIC_VECTOR (15 downto 0);
        din154 : IN STD_LOGIC_VECTOR (15 downto 0);
        din155 : IN STD_LOGIC_VECTOR (15 downto 0);
        din156 : IN STD_LOGIC_VECTOR (15 downto 0);
        din157 : IN STD_LOGIC_VECTOR (15 downto 0);
        din158 : IN STD_LOGIC_VECTOR (15 downto 0);
        din159 : IN STD_LOGIC_VECTOR (15 downto 0);
        din160 : IN STD_LOGIC_VECTOR (15 downto 0);
        din161 : IN STD_LOGIC_VECTOR (15 downto 0);
        din162 : IN STD_LOGIC_VECTOR (15 downto 0);
        din163 : IN STD_LOGIC_VECTOR (15 downto 0);
        din164 : IN STD_LOGIC_VECTOR (15 downto 0);
        din165 : IN STD_LOGIC_VECTOR (15 downto 0);
        din166 : IN STD_LOGIC_VECTOR (15 downto 0);
        din167 : IN STD_LOGIC_VECTOR (15 downto 0);
        din168 : IN STD_LOGIC_VECTOR (15 downto 0);
        din169 : IN STD_LOGIC_VECTOR (15 downto 0);
        din170 : IN STD_LOGIC_VECTOR (15 downto 0);
        din171 : IN STD_LOGIC_VECTOR (15 downto 0);
        din172 : IN STD_LOGIC_VECTOR (15 downto 0);
        din173 : IN STD_LOGIC_VECTOR (15 downto 0);
        din174 : IN STD_LOGIC_VECTOR (15 downto 0);
        din175 : IN STD_LOGIC_VECTOR (15 downto 0);
        din176 : IN STD_LOGIC_VECTOR (15 downto 0);
        din177 : IN STD_LOGIC_VECTOR (15 downto 0);
        din178 : IN STD_LOGIC_VECTOR (15 downto 0);
        din179 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hyperspectral_hw_wrapped_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_1798_16_1_1_U563 : component hyperspectral_hw_wrapped_mux_1798_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 16,
        din6_WIDTH => 16,
        din7_WIDTH => 16,
        din8_WIDTH => 16,
        din9_WIDTH => 16,
        din10_WIDTH => 16,
        din11_WIDTH => 16,
        din12_WIDTH => 16,
        din13_WIDTH => 16,
        din14_WIDTH => 16,
        din15_WIDTH => 16,
        din16_WIDTH => 16,
        din17_WIDTH => 16,
        din18_WIDTH => 16,
        din19_WIDTH => 16,
        din20_WIDTH => 16,
        din21_WIDTH => 16,
        din22_WIDTH => 16,
        din23_WIDTH => 16,
        din24_WIDTH => 16,
        din25_WIDTH => 16,
        din26_WIDTH => 16,
        din27_WIDTH => 16,
        din28_WIDTH => 16,
        din29_WIDTH => 16,
        din30_WIDTH => 16,
        din31_WIDTH => 16,
        din32_WIDTH => 16,
        din33_WIDTH => 16,
        din34_WIDTH => 16,
        din35_WIDTH => 16,
        din36_WIDTH => 16,
        din37_WIDTH => 16,
        din38_WIDTH => 16,
        din39_WIDTH => 16,
        din40_WIDTH => 16,
        din41_WIDTH => 16,
        din42_WIDTH => 16,
        din43_WIDTH => 16,
        din44_WIDTH => 16,
        din45_WIDTH => 16,
        din46_WIDTH => 16,
        din47_WIDTH => 16,
        din48_WIDTH => 16,
        din49_WIDTH => 16,
        din50_WIDTH => 16,
        din51_WIDTH => 16,
        din52_WIDTH => 16,
        din53_WIDTH => 16,
        din54_WIDTH => 16,
        din55_WIDTH => 16,
        din56_WIDTH => 16,
        din57_WIDTH => 16,
        din58_WIDTH => 16,
        din59_WIDTH => 16,
        din60_WIDTH => 16,
        din61_WIDTH => 16,
        din62_WIDTH => 16,
        din63_WIDTH => 16,
        din64_WIDTH => 16,
        din65_WIDTH => 16,
        din66_WIDTH => 16,
        din67_WIDTH => 16,
        din68_WIDTH => 16,
        din69_WIDTH => 16,
        din70_WIDTH => 16,
        din71_WIDTH => 16,
        din72_WIDTH => 16,
        din73_WIDTH => 16,
        din74_WIDTH => 16,
        din75_WIDTH => 16,
        din76_WIDTH => 16,
        din77_WIDTH => 16,
        din78_WIDTH => 16,
        din79_WIDTH => 16,
        din80_WIDTH => 16,
        din81_WIDTH => 16,
        din82_WIDTH => 16,
        din83_WIDTH => 16,
        din84_WIDTH => 16,
        din85_WIDTH => 16,
        din86_WIDTH => 16,
        din87_WIDTH => 16,
        din88_WIDTH => 16,
        din89_WIDTH => 16,
        din90_WIDTH => 16,
        din91_WIDTH => 16,
        din92_WIDTH => 16,
        din93_WIDTH => 16,
        din94_WIDTH => 16,
        din95_WIDTH => 16,
        din96_WIDTH => 16,
        din97_WIDTH => 16,
        din98_WIDTH => 16,
        din99_WIDTH => 16,
        din100_WIDTH => 16,
        din101_WIDTH => 16,
        din102_WIDTH => 16,
        din103_WIDTH => 16,
        din104_WIDTH => 16,
        din105_WIDTH => 16,
        din106_WIDTH => 16,
        din107_WIDTH => 16,
        din108_WIDTH => 16,
        din109_WIDTH => 16,
        din110_WIDTH => 16,
        din111_WIDTH => 16,
        din112_WIDTH => 16,
        din113_WIDTH => 16,
        din114_WIDTH => 16,
        din115_WIDTH => 16,
        din116_WIDTH => 16,
        din117_WIDTH => 16,
        din118_WIDTH => 16,
        din119_WIDTH => 16,
        din120_WIDTH => 16,
        din121_WIDTH => 16,
        din122_WIDTH => 16,
        din123_WIDTH => 16,
        din124_WIDTH => 16,
        din125_WIDTH => 16,
        din126_WIDTH => 16,
        din127_WIDTH => 16,
        din128_WIDTH => 16,
        din129_WIDTH => 16,
        din130_WIDTH => 16,
        din131_WIDTH => 16,
        din132_WIDTH => 16,
        din133_WIDTH => 16,
        din134_WIDTH => 16,
        din135_WIDTH => 16,
        din136_WIDTH => 16,
        din137_WIDTH => 16,
        din138_WIDTH => 16,
        din139_WIDTH => 16,
        din140_WIDTH => 16,
        din141_WIDTH => 16,
        din142_WIDTH => 16,
        din143_WIDTH => 16,
        din144_WIDTH => 16,
        din145_WIDTH => 16,
        din146_WIDTH => 16,
        din147_WIDTH => 16,
        din148_WIDTH => 16,
        din149_WIDTH => 16,
        din150_WIDTH => 16,
        din151_WIDTH => 16,
        din152_WIDTH => 16,
        din153_WIDTH => 16,
        din154_WIDTH => 16,
        din155_WIDTH => 16,
        din156_WIDTH => 16,
        din157_WIDTH => 16,
        din158_WIDTH => 16,
        din159_WIDTH => 16,
        din160_WIDTH => 16,
        din161_WIDTH => 16,
        din162_WIDTH => 16,
        din163_WIDTH => 16,
        din164_WIDTH => 16,
        din165_WIDTH => 16,
        din166_WIDTH => 16,
        din167_WIDTH => 16,
        din168_WIDTH => 16,
        din169_WIDTH => 16,
        din170_WIDTH => 16,
        din171_WIDTH => 16,
        din172_WIDTH => 16,
        din173_WIDTH => 16,
        din174_WIDTH => 16,
        din175_WIDTH => 16,
        din176_WIDTH => 16,
        din177_WIDTH => 16,
        din178_WIDTH => 16,
        din179_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => closest_pixel_V_359_04_reload,
        din1 => ap_const_lv16_0,
        din2 => closest_pixel_V_360_06_reload,
        din3 => ap_const_lv16_0,
        din4 => closest_pixel_V_361_08_reload,
        din5 => ap_const_lv16_0,
        din6 => closest_pixel_V_362_010_reload,
        din7 => ap_const_lv16_0,
        din8 => closest_pixel_V_363_012_reload,
        din9 => ap_const_lv16_0,
        din10 => closest_pixel_V_364_014_reload,
        din11 => ap_const_lv16_0,
        din12 => closest_pixel_V_365_016_reload,
        din13 => ap_const_lv16_0,
        din14 => closest_pixel_V_366_018_reload,
        din15 => ap_const_lv16_0,
        din16 => closest_pixel_V_367_020_reload,
        din17 => ap_const_lv16_0,
        din18 => closest_pixel_V_368_022_reload,
        din19 => ap_const_lv16_0,
        din20 => closest_pixel_V_369_024_reload,
        din21 => ap_const_lv16_0,
        din22 => closest_pixel_V_370_026_reload,
        din23 => ap_const_lv16_0,
        din24 => closest_pixel_V_371_028_reload,
        din25 => ap_const_lv16_0,
        din26 => closest_pixel_V_372_030_reload,
        din27 => ap_const_lv16_0,
        din28 => closest_pixel_V_373_032_reload,
        din29 => ap_const_lv16_0,
        din30 => closest_pixel_V_374_034_reload,
        din31 => ap_const_lv16_0,
        din32 => closest_pixel_V_375_036_reload,
        din33 => ap_const_lv16_0,
        din34 => closest_pixel_V_376_038_reload,
        din35 => ap_const_lv16_0,
        din36 => closest_pixel_V_377_040_reload,
        din37 => ap_const_lv16_0,
        din38 => closest_pixel_V_378_042_reload,
        din39 => ap_const_lv16_0,
        din40 => closest_pixel_V_379_044_reload,
        din41 => ap_const_lv16_0,
        din42 => closest_pixel_V_380_046_reload,
        din43 => ap_const_lv16_0,
        din44 => closest_pixel_V_381_048_reload,
        din45 => ap_const_lv16_0,
        din46 => closest_pixel_V_382_050_reload,
        din47 => ap_const_lv16_0,
        din48 => closest_pixel_V_383_052_reload,
        din49 => ap_const_lv16_0,
        din50 => closest_pixel_V_384_054_reload,
        din51 => ap_const_lv16_0,
        din52 => closest_pixel_V_385_056_reload,
        din53 => ap_const_lv16_0,
        din54 => closest_pixel_V_386_058_reload,
        din55 => ap_const_lv16_0,
        din56 => closest_pixel_V_387_060_reload,
        din57 => ap_const_lv16_0,
        din58 => closest_pixel_V_388_062_reload,
        din59 => ap_const_lv16_0,
        din60 => closest_pixel_V_389_064_reload,
        din61 => ap_const_lv16_0,
        din62 => closest_pixel_V_390_066_reload,
        din63 => ap_const_lv16_0,
        din64 => closest_pixel_V_391_068_reload,
        din65 => ap_const_lv16_0,
        din66 => closest_pixel_V_392_070_reload,
        din67 => ap_const_lv16_0,
        din68 => closest_pixel_V_393_072_reload,
        din69 => ap_const_lv16_0,
        din70 => closest_pixel_V_394_074_reload,
        din71 => ap_const_lv16_0,
        din72 => closest_pixel_V_395_076_reload,
        din73 => ap_const_lv16_0,
        din74 => closest_pixel_V_396_078_reload,
        din75 => ap_const_lv16_0,
        din76 => closest_pixel_V_397_080_reload,
        din77 => ap_const_lv16_0,
        din78 => closest_pixel_V_398_082_reload,
        din79 => ap_const_lv16_0,
        din80 => closest_pixel_V_399_084_reload,
        din81 => ap_const_lv16_0,
        din82 => closest_pixel_V_400_086_reload,
        din83 => ap_const_lv16_0,
        din84 => closest_pixel_V_401_088_reload,
        din85 => ap_const_lv16_0,
        din86 => closest_pixel_V_402_090_reload,
        din87 => ap_const_lv16_0,
        din88 => closest_pixel_V_403_092_reload,
        din89 => ap_const_lv16_0,
        din90 => closest_pixel_V_404_094_reload,
        din91 => ap_const_lv16_0,
        din92 => closest_pixel_V_405_096_reload,
        din93 => ap_const_lv16_0,
        din94 => closest_pixel_V_406_098_reload,
        din95 => ap_const_lv16_0,
        din96 => closest_pixel_V_407_0100_reload,
        din97 => ap_const_lv16_0,
        din98 => closest_pixel_V_408_0102_reload,
        din99 => ap_const_lv16_0,
        din100 => closest_pixel_V_409_0104_reload,
        din101 => ap_const_lv16_0,
        din102 => closest_pixel_V_410_0106_reload,
        din103 => ap_const_lv16_0,
        din104 => closest_pixel_V_411_0108_reload,
        din105 => ap_const_lv16_0,
        din106 => closest_pixel_V_412_0110_reload,
        din107 => ap_const_lv16_0,
        din108 => closest_pixel_V_413_0112_reload,
        din109 => ap_const_lv16_0,
        din110 => closest_pixel_V_414_0114_reload,
        din111 => ap_const_lv16_0,
        din112 => closest_pixel_V_415_0116_reload,
        din113 => ap_const_lv16_0,
        din114 => closest_pixel_V_416_0118_reload,
        din115 => ap_const_lv16_0,
        din116 => closest_pixel_V_417_0120_reload,
        din117 => ap_const_lv16_0,
        din118 => closest_pixel_V_418_0122_reload,
        din119 => ap_const_lv16_0,
        din120 => closest_pixel_V_419_0124_reload,
        din121 => ap_const_lv16_0,
        din122 => closest_pixel_V_420_0126_reload,
        din123 => ap_const_lv16_0,
        din124 => closest_pixel_V_421_0128_reload,
        din125 => ap_const_lv16_0,
        din126 => closest_pixel_V_422_0130_reload,
        din127 => ap_const_lv16_0,
        din128 => closest_pixel_V_423_0132_reload,
        din129 => ap_const_lv16_0,
        din130 => closest_pixel_V_424_0134_reload,
        din131 => ap_const_lv16_0,
        din132 => closest_pixel_V_425_0136_reload,
        din133 => ap_const_lv16_0,
        din134 => closest_pixel_V_426_0138_reload,
        din135 => ap_const_lv16_0,
        din136 => closest_pixel_V_427_0140_reload,
        din137 => ap_const_lv16_0,
        din138 => closest_pixel_V_428_0142_reload,
        din139 => ap_const_lv16_0,
        din140 => closest_pixel_V_429_0144_reload,
        din141 => ap_const_lv16_0,
        din142 => closest_pixel_V_430_0146_reload,
        din143 => ap_const_lv16_0,
        din144 => closest_pixel_V_431_0148_reload,
        din145 => ap_const_lv16_0,
        din146 => closest_pixel_V_432_0150_reload,
        din147 => ap_const_lv16_0,
        din148 => closest_pixel_V_433_0152_reload,
        din149 => ap_const_lv16_0,
        din150 => closest_pixel_V_434_0154_reload,
        din151 => ap_const_lv16_0,
        din152 => closest_pixel_V_435_0156_reload,
        din153 => ap_const_lv16_0,
        din154 => closest_pixel_V_436_0158_reload,
        din155 => ap_const_lv16_0,
        din156 => closest_pixel_V_437_0160_reload,
        din157 => ap_const_lv16_0,
        din158 => closest_pixel_V_438_0162_reload,
        din159 => ap_const_lv16_0,
        din160 => closest_pixel_V_439_0164_reload,
        din161 => ap_const_lv16_0,
        din162 => closest_pixel_V_440_0166_reload,
        din163 => ap_const_lv16_0,
        din164 => closest_pixel_V_441_0168_reload,
        din165 => ap_const_lv16_0,
        din166 => closest_pixel_V_442_0170_reload,
        din167 => ap_const_lv16_0,
        din168 => closest_pixel_V_443_0172_reload,
        din169 => ap_const_lv16_0,
        din170 => closest_pixel_V_444_0174_reload,
        din171 => ap_const_lv16_0,
        din172 => closest_pixel_V_445_0176_reload,
        din173 => ap_const_lv16_0,
        din174 => closest_pixel_V_446_0178_reload,
        din175 => ap_const_lv16_0,
        din176 => closest_pixel_V_447_0180_reload,
        din177 => ap_const_lv16_0,
        din178 => closest_pixel_V_448_0182_reload,
        din179 => ap_sig_allocacmp_i_1,
        dout => tmp_s_fu_1552_p181);

    mux_1798_16_1_1_U564 : component hyperspectral_hw_wrapped_mux_1798_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 16,
        din3_WIDTH => 16,
        din4_WIDTH => 16,
        din5_WIDTH => 16,
        din6_WIDTH => 16,
        din7_WIDTH => 16,
        din8_WIDTH => 16,
        din9_WIDTH => 16,
        din10_WIDTH => 16,
        din11_WIDTH => 16,
        din12_WIDTH => 16,
        din13_WIDTH => 16,
        din14_WIDTH => 16,
        din15_WIDTH => 16,
        din16_WIDTH => 16,
        din17_WIDTH => 16,
        din18_WIDTH => 16,
        din19_WIDTH => 16,
        din20_WIDTH => 16,
        din21_WIDTH => 16,
        din22_WIDTH => 16,
        din23_WIDTH => 16,
        din24_WIDTH => 16,
        din25_WIDTH => 16,
        din26_WIDTH => 16,
        din27_WIDTH => 16,
        din28_WIDTH => 16,
        din29_WIDTH => 16,
        din30_WIDTH => 16,
        din31_WIDTH => 16,
        din32_WIDTH => 16,
        din33_WIDTH => 16,
        din34_WIDTH => 16,
        din35_WIDTH => 16,
        din36_WIDTH => 16,
        din37_WIDTH => 16,
        din38_WIDTH => 16,
        din39_WIDTH => 16,
        din40_WIDTH => 16,
        din41_WIDTH => 16,
        din42_WIDTH => 16,
        din43_WIDTH => 16,
        din44_WIDTH => 16,
        din45_WIDTH => 16,
        din46_WIDTH => 16,
        din47_WIDTH => 16,
        din48_WIDTH => 16,
        din49_WIDTH => 16,
        din50_WIDTH => 16,
        din51_WIDTH => 16,
        din52_WIDTH => 16,
        din53_WIDTH => 16,
        din54_WIDTH => 16,
        din55_WIDTH => 16,
        din56_WIDTH => 16,
        din57_WIDTH => 16,
        din58_WIDTH => 16,
        din59_WIDTH => 16,
        din60_WIDTH => 16,
        din61_WIDTH => 16,
        din62_WIDTH => 16,
        din63_WIDTH => 16,
        din64_WIDTH => 16,
        din65_WIDTH => 16,
        din66_WIDTH => 16,
        din67_WIDTH => 16,
        din68_WIDTH => 16,
        din69_WIDTH => 16,
        din70_WIDTH => 16,
        din71_WIDTH => 16,
        din72_WIDTH => 16,
        din73_WIDTH => 16,
        din74_WIDTH => 16,
        din75_WIDTH => 16,
        din76_WIDTH => 16,
        din77_WIDTH => 16,
        din78_WIDTH => 16,
        din79_WIDTH => 16,
        din80_WIDTH => 16,
        din81_WIDTH => 16,
        din82_WIDTH => 16,
        din83_WIDTH => 16,
        din84_WIDTH => 16,
        din85_WIDTH => 16,
        din86_WIDTH => 16,
        din87_WIDTH => 16,
        din88_WIDTH => 16,
        din89_WIDTH => 16,
        din90_WIDTH => 16,
        din91_WIDTH => 16,
        din92_WIDTH => 16,
        din93_WIDTH => 16,
        din94_WIDTH => 16,
        din95_WIDTH => 16,
        din96_WIDTH => 16,
        din97_WIDTH => 16,
        din98_WIDTH => 16,
        din99_WIDTH => 16,
        din100_WIDTH => 16,
        din101_WIDTH => 16,
        din102_WIDTH => 16,
        din103_WIDTH => 16,
        din104_WIDTH => 16,
        din105_WIDTH => 16,
        din106_WIDTH => 16,
        din107_WIDTH => 16,
        din108_WIDTH => 16,
        din109_WIDTH => 16,
        din110_WIDTH => 16,
        din111_WIDTH => 16,
        din112_WIDTH => 16,
        din113_WIDTH => 16,
        din114_WIDTH => 16,
        din115_WIDTH => 16,
        din116_WIDTH => 16,
        din117_WIDTH => 16,
        din118_WIDTH => 16,
        din119_WIDTH => 16,
        din120_WIDTH => 16,
        din121_WIDTH => 16,
        din122_WIDTH => 16,
        din123_WIDTH => 16,
        din124_WIDTH => 16,
        din125_WIDTH => 16,
        din126_WIDTH => 16,
        din127_WIDTH => 16,
        din128_WIDTH => 16,
        din129_WIDTH => 16,
        din130_WIDTH => 16,
        din131_WIDTH => 16,
        din132_WIDTH => 16,
        din133_WIDTH => 16,
        din134_WIDTH => 16,
        din135_WIDTH => 16,
        din136_WIDTH => 16,
        din137_WIDTH => 16,
        din138_WIDTH => 16,
        din139_WIDTH => 16,
        din140_WIDTH => 16,
        din141_WIDTH => 16,
        din142_WIDTH => 16,
        din143_WIDTH => 16,
        din144_WIDTH => 16,
        din145_WIDTH => 16,
        din146_WIDTH => 16,
        din147_WIDTH => 16,
        din148_WIDTH => 16,
        din149_WIDTH => 16,
        din150_WIDTH => 16,
        din151_WIDTH => 16,
        din152_WIDTH => 16,
        din153_WIDTH => 16,
        din154_WIDTH => 16,
        din155_WIDTH => 16,
        din156_WIDTH => 16,
        din157_WIDTH => 16,
        din158_WIDTH => 16,
        din159_WIDTH => 16,
        din160_WIDTH => 16,
        din161_WIDTH => 16,
        din162_WIDTH => 16,
        din163_WIDTH => 16,
        din164_WIDTH => 16,
        din165_WIDTH => 16,
        din166_WIDTH => 16,
        din167_WIDTH => 16,
        din168_WIDTH => 16,
        din169_WIDTH => 16,
        din170_WIDTH => 16,
        din171_WIDTH => 16,
        din172_WIDTH => 16,
        din173_WIDTH => 16,
        din174_WIDTH => 16,
        din175_WIDTH => 16,
        din176_WIDTH => 16,
        din177_WIDTH => 16,
        din178_WIDTH => 16,
        din179_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => closest_pixel_V_449_05_reload,
        din1 => ap_const_lv16_0,
        din2 => closest_pixel_V_450_07_reload,
        din3 => ap_const_lv16_0,
        din4 => closest_pixel_V_451_09_reload,
        din5 => ap_const_lv16_0,
        din6 => closest_pixel_V_452_011_reload,
        din7 => ap_const_lv16_0,
        din8 => closest_pixel_V_453_013_reload,
        din9 => ap_const_lv16_0,
        din10 => closest_pixel_V_454_015_reload,
        din11 => ap_const_lv16_0,
        din12 => closest_pixel_V_455_017_reload,
        din13 => ap_const_lv16_0,
        din14 => closest_pixel_V_456_019_reload,
        din15 => ap_const_lv16_0,
        din16 => closest_pixel_V_457_021_reload,
        din17 => ap_const_lv16_0,
        din18 => closest_pixel_V_458_023_reload,
        din19 => ap_const_lv16_0,
        din20 => closest_pixel_V_459_025_reload,
        din21 => ap_const_lv16_0,
        din22 => closest_pixel_V_460_027_reload,
        din23 => ap_const_lv16_0,
        din24 => closest_pixel_V_461_029_reload,
        din25 => ap_const_lv16_0,
        din26 => closest_pixel_V_462_031_reload,
        din27 => ap_const_lv16_0,
        din28 => closest_pixel_V_463_033_reload,
        din29 => ap_const_lv16_0,
        din30 => closest_pixel_V_464_035_reload,
        din31 => ap_const_lv16_0,
        din32 => closest_pixel_V_465_037_reload,
        din33 => ap_const_lv16_0,
        din34 => closest_pixel_V_466_039_reload,
        din35 => ap_const_lv16_0,
        din36 => closest_pixel_V_467_041_reload,
        din37 => ap_const_lv16_0,
        din38 => closest_pixel_V_468_043_reload,
        din39 => ap_const_lv16_0,
        din40 => closest_pixel_V_469_045_reload,
        din41 => ap_const_lv16_0,
        din42 => closest_pixel_V_470_047_reload,
        din43 => ap_const_lv16_0,
        din44 => closest_pixel_V_471_049_reload,
        din45 => ap_const_lv16_0,
        din46 => closest_pixel_V_472_051_reload,
        din47 => ap_const_lv16_0,
        din48 => closest_pixel_V_473_053_reload,
        din49 => ap_const_lv16_0,
        din50 => closest_pixel_V_474_055_reload,
        din51 => ap_const_lv16_0,
        din52 => closest_pixel_V_475_057_reload,
        din53 => ap_const_lv16_0,
        din54 => closest_pixel_V_476_059_reload,
        din55 => ap_const_lv16_0,
        din56 => closest_pixel_V_477_061_reload,
        din57 => ap_const_lv16_0,
        din58 => closest_pixel_V_478_063_reload,
        din59 => ap_const_lv16_0,
        din60 => closest_pixel_V_479_065_reload,
        din61 => ap_const_lv16_0,
        din62 => closest_pixel_V_480_067_reload,
        din63 => ap_const_lv16_0,
        din64 => closest_pixel_V_481_069_reload,
        din65 => ap_const_lv16_0,
        din66 => closest_pixel_V_482_071_reload,
        din67 => ap_const_lv16_0,
        din68 => closest_pixel_V_483_073_reload,
        din69 => ap_const_lv16_0,
        din70 => closest_pixel_V_484_075_reload,
        din71 => ap_const_lv16_0,
        din72 => closest_pixel_V_485_077_reload,
        din73 => ap_const_lv16_0,
        din74 => closest_pixel_V_486_079_reload,
        din75 => ap_const_lv16_0,
        din76 => closest_pixel_V_487_081_reload,
        din77 => ap_const_lv16_0,
        din78 => closest_pixel_V_488_083_reload,
        din79 => ap_const_lv16_0,
        din80 => closest_pixel_V_489_085_reload,
        din81 => ap_const_lv16_0,
        din82 => closest_pixel_V_490_087_reload,
        din83 => ap_const_lv16_0,
        din84 => closest_pixel_V_491_089_reload,
        din85 => ap_const_lv16_0,
        din86 => closest_pixel_V_492_091_reload,
        din87 => ap_const_lv16_0,
        din88 => closest_pixel_V_493_093_reload,
        din89 => ap_const_lv16_0,
        din90 => closest_pixel_V_494_095_reload,
        din91 => ap_const_lv16_0,
        din92 => closest_pixel_V_495_097_reload,
        din93 => ap_const_lv16_0,
        din94 => closest_pixel_V_496_099_reload,
        din95 => ap_const_lv16_0,
        din96 => closest_pixel_V_497_0101_reload,
        din97 => ap_const_lv16_0,
        din98 => closest_pixel_V_498_0103_reload,
        din99 => ap_const_lv16_0,
        din100 => closest_pixel_V_499_0105_reload,
        din101 => ap_const_lv16_0,
        din102 => closest_pixel_V_500_0107_reload,
        din103 => ap_const_lv16_0,
        din104 => closest_pixel_V_501_0109_reload,
        din105 => ap_const_lv16_0,
        din106 => closest_pixel_V_502_0111_reload,
        din107 => ap_const_lv16_0,
        din108 => closest_pixel_V_503_0113_reload,
        din109 => ap_const_lv16_0,
        din110 => closest_pixel_V_504_0115_reload,
        din111 => ap_const_lv16_0,
        din112 => closest_pixel_V_505_0117_reload,
        din113 => ap_const_lv16_0,
        din114 => closest_pixel_V_506_0119_reload,
        din115 => ap_const_lv16_0,
        din116 => closest_pixel_V_507_0121_reload,
        din117 => ap_const_lv16_0,
        din118 => closest_pixel_V_508_0123_reload,
        din119 => ap_const_lv16_0,
        din120 => closest_pixel_V_509_0125_reload,
        din121 => ap_const_lv16_0,
        din122 => closest_pixel_V_510_0127_reload,
        din123 => ap_const_lv16_0,
        din124 => closest_pixel_V_511_0129_reload,
        din125 => ap_const_lv16_0,
        din126 => closest_pixel_V_512_0131_reload,
        din127 => ap_const_lv16_0,
        din128 => closest_pixel_V_513_0133_reload,
        din129 => ap_const_lv16_0,
        din130 => closest_pixel_V_514_0135_reload,
        din131 => ap_const_lv16_0,
        din132 => closest_pixel_V_515_0137_reload,
        din133 => ap_const_lv16_0,
        din134 => closest_pixel_V_516_0139_reload,
        din135 => ap_const_lv16_0,
        din136 => closest_pixel_V_517_0141_reload,
        din137 => ap_const_lv16_0,
        din138 => closest_pixel_V_518_0143_reload,
        din139 => ap_const_lv16_0,
        din140 => closest_pixel_V_519_0145_reload,
        din141 => ap_const_lv16_0,
        din142 => closest_pixel_V_520_0147_reload,
        din143 => ap_const_lv16_0,
        din144 => closest_pixel_V_521_0149_reload,
        din145 => ap_const_lv16_0,
        din146 => closest_pixel_V_522_0151_reload,
        din147 => ap_const_lv16_0,
        din148 => closest_pixel_V_523_0153_reload,
        din149 => ap_const_lv16_0,
        din150 => closest_pixel_V_524_0155_reload,
        din151 => ap_const_lv16_0,
        din152 => closest_pixel_V_525_0157_reload,
        din153 => ap_const_lv16_0,
        din154 => closest_pixel_V_526_0159_reload,
        din155 => ap_const_lv16_0,
        din156 => closest_pixel_V_527_0161_reload,
        din157 => ap_const_lv16_0,
        din158 => closest_pixel_V_528_0163_reload,
        din159 => ap_const_lv16_0,
        din160 => closest_pixel_V_529_0165_reload,
        din161 => ap_const_lv16_0,
        din162 => closest_pixel_V_530_0167_reload,
        din163 => ap_const_lv16_0,
        din164 => closest_pixel_V_531_0169_reload,
        din165 => ap_const_lv16_0,
        din166 => closest_pixel_V_532_0171_reload,
        din167 => ap_const_lv16_0,
        din168 => closest_pixel_V_533_0173_reload,
        din169 => ap_const_lv16_0,
        din170 => closest_pixel_V_534_0175_reload,
        din171 => ap_const_lv16_0,
        din172 => closest_pixel_V_535_0177_reload,
        din173 => ap_const_lv16_0,
        din174 => closest_pixel_V_536_0179_reload,
        din175 => ap_const_lv16_0,
        din176 => closest_pixel_V_537_0181_reload,
        din177 => ap_const_lv16_0,
        din178 => closest_pixel_V_538_0183_reload,
        din179 => ap_sig_allocacmp_i_1,
        dout => tmp_27_fu_1916_p181);

    flow_control_loop_pipe_sequential_init_U : component hyperspectral_hw_wrapped_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln85_fu_1546_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_424 <= add_ln85_fu_2286_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_424 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln85_fu_1546_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                e_last_V_reg_2324 <= e_last_V_fu_2280_p2;
                tmp_27_reg_2319 <= tmp_27_fu_1916_p181;
                tmp_s_reg_2314 <= tmp_s_fu_1552_p181;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln85_fu_2286_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv8_2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_01001 <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, out_stream_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((out_stream_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(out_stream_TREADY)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (out_stream_TREADY = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln85_fu_1546_p2)
    begin
        if (((icmp_ln85_fu_1546_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_424, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_424;
        end if; 
    end process;

    e_last_V_fu_2280_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) > unsigned(ap_const_lv8_B1)) else "0";
    icmp_ln85_fu_1546_p2 <= "1" when (unsigned(ap_sig_allocacmp_i_1) < unsigned(ap_const_lv8_B4)) else "0";
    out_stream_TDATA <= (tmp_27_reg_2319 & tmp_s_reg_2314);

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, out_stream_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDEST <= ap_const_lv5_6;
    out_stream_TID <= ap_const_lv5_5;
    out_stream_TKEEP <= ap_const_lv4_F;
    out_stream_TLAST <= e_last_V_reg_2324;
    out_stream_TSTRB <= ap_const_lv4_F;
    out_stream_TUSER <= ap_const_lv4_0;

    out_stream_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            out_stream_TVALID <= ap_const_logic_1;
        else 
            out_stream_TVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
